[package]
name = "nINIParse"
version = "1.0.0"
authors = ["nothus - Julien Garderon <julien.garderon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
